import os
import sys
import logging
from typing import List
from dotenv import load_dotenv

# Load env credentials
load_dotenv()

logger = logging.getLogger("embedder")

class LegalEmbedder:
    """
    Converts text chunks into dense vector embeddings.
    Supports local SentenceTransformers (multilingual-e5) or OpenAI API.
    """
    def __init__(self, use_openai: bool = False, model_name: str = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"):
        self.use_openai = use_openai
        self.model_name = model_name
        self.openai_key = os.getenv("OPENAI_API_KEY")
        self.model = None
        self.client = None
        
        if self.use_openai and self.openai_key:
            try:
                from openai import OpenAI
                self.client = OpenAI(api_key=self.openai_key)
                logger.info("Initialized OpenAI Client for embeddings.")
            except ImportError:
                logger.warning("openai package not installed. Falling back to local SentenceTransformer.")
                self.use_openai = False
                
        if not self.use_openai:
            logger.info(f"Loading local SentenceTransformer model: {model_name}...")
            try:
                from sentence_transformers import SentenceTransformer
                self.model = SentenceTransformer(model_name)
                logger.info("Successfully loaded SentenceTransformer model.")
            except Exception as e:
                logger.error(f"Failed to load SentenceTransformer: {e}")
                raise

    def get_embedding_dimension(self) -> int:
        """Returns the length of the vector generated by this embedder."""
        if self.use_openai:
            return 1536  # Default dimension for text-embedding-3-small or ada-002
        else:
            # Get dimension from model config
            return self.model.get_sentence_embedding_dimension()

    def embed_query(self, text: str) -> List[float]:
        """Generates a vector embedding for a single search query."""
        if not text:
            return []
        embeddings = self.embed_texts([text])
        return embeddings[0] if embeddings else []

    def embed_texts(self, texts: List[str]) -> List[List[float]]:
        """Generates embeddings for a batch of text snippets."""
        if not texts:
            return []
            
        if self.use_openai and self.client:
            try:
                response = self.client.embeddings.create(
                    input=texts,
                    model="text-embedding-3-small"
                )
                return [data.embedding for data in response.data]
            except Exception as e:
                logger.error(f"OpenAI Embedding API failed: {e}. Falling back to local model if loaded.")
                if not self.model:
                    raise e
                    
        # Fallback/Default to local SentenceTransformer
        if self.model:
            # Convert texts to embeddings list
            import numpy as np
            embeddings = self.model.encode(texts, show_progress_bar=False)
            # Convert NumPy array to Python list of floats
            return embeddings.tolist()
            
        return []

if __name__ == "__main__":
    # Test local multilingual embedder
    logging.basicConfig(level=logging.INFO)
    embedder = LegalEmbedder()
    test_text = "नेपालको स्वतन्त्रता, सार्वभौमसत्ता, भौगोलिक अखण्डता"
    
    vector = embedder.embed_query(test_text)
    print("Test text:", test_text)
    print("Embedding Vector length:", len(vector))
    print("Embedding Vector preview (first 5 elements):", vector[:5])
